import { useEffect, useMemo, useState } from "react"
import { Building2, CheckCircle2, Search, ShieldAlert, UserRound } from "lucide-react"
import { platform } from "../../api/api"
import { err } from "../../utils/helpers"
import "../../styles/platform.css"
export default function Gyms(){const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState("all")
 const load=async()=>{setLoading(true);try{const d=await platform.gyms();setRows(d?.gyms||[])}catch(e){setError(err(e))}finally{setLoading(false)}};useEffect(()=>{load()},[])
 const filtered=useMemo(()=>rows.filter(g=>(filter==="all"||(filter==="active"?g.isActive:!g.isActive))&&(`${g.name} ${g.owner?.email||""} ${g.subscription?.plan?.name||""}`).toLowerCase().includes(query.toLowerCase())),[rows,query,filter])
 const toggle=async g=>{try{await platform.updateGym(g._id,{isActive:!g.isActive});load()}catch(e){setError(err(e))}}
 return <div className="platform-page"><div className="platform-wrap"><Header title="Gyms" desc="Manage every tenant on the GB platform." icon={Building2}/>{error&&<div className="p-alert error">{error}</div>}
 <div className="p-kpi-strip" style={{marginBottom:16}}><Mini label="Total gyms" value={rows.length}/><Mini label="Active" value={rows.filter(x=>x.isActive).length}/><Mini label="Suspended" value={rows.filter(x=>!x.isActive).length}/></div>
 <section className="p-panel"><div className="p-toolbar"><div className="p-search"><Search size={16}/><input placeholder="Search gym, owner or plan..." value={query} onChange={e=>setQuery(e.target.value)}/></div><select className="p-select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All gyms</option><option value="active">Active</option><option value="suspended">Suspended</option></select></div>
 {loading?<div className="p-empty">Loading gyms...</div>:filtered.length?<div className="p-table-wrap"><table className="p-table"><thead><tr><th>Gym</th><th>Owner</th><th>Plan</th><th>Subscription</th><th>Access</th><th>Action</th></tr></thead><tbody>{filtered.map(g=><tr key={g._id}><td><div className="p-gym"><div className="p-gym-logo">{(g.name||"G").slice(0,1).toUpperCase()}</div><div><b>{g.name}</b><span>{g.city||g.state||"GB tenant"}</span></div></div></td><td><span className="p-muted">{g.owner?.email||"—"}</span></td><td><b>{g.subscription?.plan?.name||g.subscription?.planName||"—"}</b></td><td><Badge value={g.subscription?.status||"none"}/></td><td><Badge value={g.isActive?"active":"suspended"}/></td><td><button className={`p-btn small ${g.isActive?"danger":"primary"}`} onClick={()=>toggle(g)}>{g.isActive?"Suspend":"Activate"}</button></td></tr>)}</tbody></table></div>:<Empty/>}</section></div></div>}
function Header({title,desc,icon:Icon}){return <div className="platform-head"><div><div className="platform-eyebrow"><i/><Icon size={13}/>&nbsp; TENANT MANAGEMENT</div><h1>{title}</h1><p>{desc}</p></div></div>};function Mini({label,value}){return <div className="p-mini"><span>{label}</span><strong>{value}</strong></div>};function Badge({value}){const v=String(value||"none").toLowerCase();return <span className={`p-badge ${v}`}>{value||"—"}</span>};function Empty(){return <div className="p-empty"><div className="p-empty-icon"><ShieldAlert size={22}/></div><h3>No gyms found</h3><p>Try another search or filter.</p></div>}
