import { useEffect, useState } from "react"
import { Check, Edit3, Package, Plus, Power, Trash2, X } from "lucide-react"
import { platform } from "../../api/api"
import { money, err } from "../../utils/helpers"
import "../../styles/platform.css"
const blank={name:"",description:"",price:"",currency:"NGN",billingCycle:"monthly",trialDays:0,maxMembers:"",maxTrainers:"",features:"",active:true,displayOrder:0}
export default function Plans(){const [plans,setPlans]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[modal,setModal]=useState(null)
 const load=async()=>{setLoading(true);try{const d=await platform.plans.list();setPlans(d?.plans||d||[])}catch(e){setError(err(e))}finally{setLoading(false)}};useEffect(()=>{load()},[])
 const save=async form=>{try{const payload={...form,price:Number(form.price||0),trialDays:Number(form.trialDays||0),maxMembers:form.maxMembers===""?null:Number(form.maxMembers),maxTrainers:form.maxTrainers===""?null:Number(form.maxTrainers),displayOrder:Number(form.displayOrder||0),features:Array.isArray(form.features)?form.features: String(form.features||"").split(",").map(x=>x.trim()).filter(Boolean)};if(form._id)await platform.plans.update(form._id,payload);else await platform.plans.create(payload);setModal(null);load()}catch(e){setError(err(e))}}
 const remove=async p=>{if(!window.confirm(`Archive ${p.name}?`))return;try{await platform.plans.remove(p._id);load()}catch(e){setError(err(e))}}
 return <div className="platform-page"><div className="platform-wrap"><div className="platform-head"><div><div className="platform-eyebrow"><i/><Package size={13}/>&nbsp; COMMERCIAL CONTROL</div><h1>SaaS Plans</h1><p>Design the plans gyms purchase to access the GB platform.</p></div><button className="p-btn primary" onClick={()=>setModal({...blank})}><Plus size={16}/>New plan</button></div>{error&&<div className="p-alert error">{error}</div>}{loading?<div className="p-empty">Loading plans...</div>:<div className="p-cards">{plans.map((p,i)=><Plan key={p._id||i} p={p} featured={i===1} onEdit={()=>setModal({...p,features:Array.isArray(p.features)?p.features.join(", "):p.features||""})} onRemove={()=>remove(p)}/>)}</div>}{modal&&<PlanModal value={modal} onClose={()=>setModal(null)} onSave={save}/>}</div></div>}
function Plan({p,featured,onEdit,onRemove}){const features=Array.isArray(p.features)?p.features:[].concat(String(p.features||"").split(",").filter(Boolean));return <div className={`p-plan ${featured?"featured":""}`}>{featured&&<span className="p-plan-tag">POPULAR</span>}<h3>{p.name}</h3><p className="p-plan-desc">{p.description||"Flexible gym management on GB."}</p><div className="p-plan-price">{money(p.price,p.currency)} <span>/ {p.billingCycle||"monthly"}</span></div><div style={{marginTop:9}}><span className={`p-badge ${p.active?"active":"suspended"}`}>{p.active?"Active":"Inactive"}</span></div><ul className="p-plan-features">{features.slice(0,6).map((f,i)=><li key={i}><Check size={14}/>{f}</li>)}{!features.length&&<li><Check size={14}/>Core GB platform features</li>}<li><Check size={14}/>{p.maxMembers==null?"Unlimited members":`${p.maxMembers} members`}</li><li><Check size={14}/>{p.maxTrainers==null?"Unlimited trainers":`${p.maxTrainers} trainers`}</li></ul><div style={{display:"flex",gap:8}}><button className="p-btn small" onClick={onEdit}><Edit3 size={13}/>Edit</button><button className="p-btn small danger" onClick={onRemove}><Trash2 size={13}/>Archive</button></div></div>}
function PlanModal({value,onClose,onSave}){const [f,setF]=useState(value),[saving,setSaving]=useState(false);const change=(k,v)=>setF(x=>({...x,[k]:v}));const submit=async e=>{e.preventDefault();setSaving(true);try{await onSave(f)}finally{setSaving(false)}};return <div className="p-modal-backdrop" onMouseDown={onClose}><div className="p-modal" onMouseDown={e=>e.stopPropagation()}><div className="p-modal-head"><div><div className="platform-eyebrow"><i/>PLAN BUILDER</div><h2>{f._id?"Edit SaaS plan":"Create SaaS plan"}</h2></div><button className="p-close" onClick={onClose}><X size={18}/></button></div><form onSubmit={submit}><div className="p-form-grid"><Field label="Plan name" value={f.name} onChange={v=>change("name",v)} required/><Field label="Currency" value={f.currency} onChange={v=>change("currency",v)}/><Field label="Price" type="number" value={f.price} onChange={v=>change("price",v)}/><Field label="Billing cycle" select options={["monthly","yearly"]} value={f.billingCycle} onChange={v=>change("billingCycle",v)}/><Field label="Trial days" type="number" value={f.trialDays} onChange={v=>change("trialDays",v)}/><Field label="Display order" type="number" value={f.displayOrder} onChange={v=>change("displayOrder",v)}/><Field label="Member limit" type="number" value={f.maxMembers??""} onChange={v=>change("maxMembers",v)} placeholder="Blank = unlimited"/><Field label="Trainer limit" type="number" value={f.maxTrainers??""} onChange={v=>change("maxTrainers",v)} placeholder="Blank = unlimited"/><Field full label="Description" textarea value={f.description} onChange={v=>change("description",v)}/><Field full label="Features (comma separated)" value={f.features} onChange={v=>change("features",v)}/></div><div className="p-form-actions"><button type="button" className="p-btn" onClick={onClose}>Cancel</button><button className="p-btn primary" disabled={saving}>{saving?"Saving...":"Save plan"}</button></div></form></div></div>}
function Field({label,value,onChange,type="text",select,options,textarea,full,placeholder}){return <div className={`p-field ${full?"full":""}`}><label>{label}</label>{textarea?<textarea value={value||""} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>:select?<select value={value||""} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select>:<input type={type} value={value??""} onChange={e=>onChange(e.target.value)} placeholder={placeholder} required={label==="Plan name"}/>}</div>}
