import { useEffect, useMemo, useState } from "react"
import {
  ArrowUpRight,
  CircleCheck,
  CircleDollarSign,
  Search,
  Trash2,
  TrendingUp,
  X,
} from "lucide-react"
import { platform } from "../../api/api"
import { money, date, err } from "../../utils/helpers"
import "../../styles/platform.css"

export default function Revenue() {
  const [data, setData] = useState({
    summary: {},
    transactions: [],
  })
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  const [query, setQuery] = useState("")
  const [cleanupLoading, setCleanupLoading] = useState(false)
  const [cleanupMessage, setCleanupMessage] = useState("")
  const [modal, setModal] = useState(null)

  const loadRevenue = async () => {
    setLoading(true)
    setError("")

    try {
      const result = await platform.revenue()
      setData(
        result || {
          summary: {},
          transactions: [],
        },
      )
    } catch (e) {
      const message = err(e)
      setError(message)
      setModal({
        type: "error",
        title: "Unable to load revenue",
        message,
      })
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadRevenue()
  }, [])

  const tx = useMemo(() => {
    const q = query.toLowerCase().trim()

    return (data.transactions || []).filter((x) =>
      `${x.gym?.name || ""} ${x.plan?.name || ""} ${x.reference || ""}`
        .toLowerCase()
        .includes(q),
    )
  }, [data.transactions, query])

  const byPlan = data.summary?.byPlan || []

  const openCleanupConfirmation = () => {
    setModal({
      type: "confirm",
      title: "Clean up transactions?",
      message:
        "This will permanently remove eligible pending/failed transactions and transactions left behind after a gym was deleted. Successful payments belonging to an existing gym will not be deleted.",
    })
  }

  const handleCleanup = async () => {
    setModal(null)
    setCleanupLoading(true)
    setCleanupMessage("")
    setError("")

    try {
      const result =
        await platform.cleanupRevenueTestData()

      const message =
        result?.message ||
        "Transaction cleanup completed successfully."

      setCleanupMessage(message)
      await loadRevenue()

      setModal({
        type: "success",
        title: "Cleanup successful",
        message,
      })
    } catch (e) {
      const message = err(e)
      setError(message)
      setModal({
        type: "error",
        title: "Cleanup could not be completed",
        message,
      })
    } finally {
      setCleanupLoading(false)
    }
  }

  return (
    <>
      <style>{`
        .revenue-responsive {
          width: 100%;
          min-width: 0;
        }

        .revenue-cleanup-head {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 18px;
        }

        .revenue-cleanup-copy {
          min-width: 0;
        }

        .revenue-cleanup-button {
          flex: 0 0 auto;
          white-space: nowrap;
        }

        .revenue-cleanup-note {
          margin-top: 14px;
        }

        .revenue-ledger-panel,
        .revenue-plan-panel {
          min-width: 0;
          width: 100%;
          overflow: hidden;
        }

        .revenue-lower-stack {
          display: grid;
          grid-template-columns: minmax(0, 1fr);
          gap: 20px;
        }

        .revenue-table-scroll {
          width: 100%;
          overflow-x: auto;
          -webkit-overflow-scrolling: touch;
        }

        @media (max-width: 900px) {
          .revenue-cleanup-head {
            flex-direction: column;
            align-items: stretch;
            gap: 14px;
          }

          .revenue-cleanup-button {
            width: 100%;
            justify-content: center;
          }
        }

        @media (max-width: 640px) {
          .revenue-responsive .platform-wrap {
            width: 100%;
            max-width: 100%;
            min-width: 0;
          }

          .revenue-responsive .p-panel {
            min-width: 0;
          }

          .revenue-responsive .platform-stats {
            grid-template-columns: minmax(0, 1fr) !important;
          }

          .revenue-cleanup-note {
            font-size: 11px;
          }

          .revenue-responsive .p-table {
            min-width: 680px;
          }
        }
      `}</style>

      <div className="platform-page revenue-responsive">
      <div className="platform-wrap">
        <div className="platform-head">
          <div>
            <div className="platform-eyebrow">
              <i />
              <CircleDollarSign size={13} />
              &nbsp; FINANCIAL CONTROL
            </div>
            <h1>Platform Revenue</h1>
            <p>
              Revenue generated by GB SaaS subscriptions only — never gym
              member payments.
            </p>
          </div>
        </div>


        {modal && (
          <RevenueModal
            modal={modal}
            onCancel={() => setModal(null)}
            onConfirm={handleCleanup}
          />
        )}

        <div className="platform-stats">
          <Stat
            label="Total revenue"
            value={money(data.summary?.total || 0)}
            icon={CircleDollarSign}
          />
          <Stat
            label="This month"
            value={money(data.summary?.monthly || 0)}
            icon={TrendingUp}
          />
          <Stat
            label="Successful payments"
            value={data.summary?.count || 0}
            icon={ArrowUpRight}
          />
          <Stat
            label="Plans generating revenue"
            value={byPlan.length}
            icon={CircleDollarSign}
            yellow
          />
        </div>

        <section
          className="p-panel"
          style={{ marginBottom: 20 }}
        >
          <div
            className="p-panel-head"
            style={{ alignItems: "center" }}
          >
            <div>
              <h3 className="p-panel-title">
                Transaction cleanup
              </h3>
              <p className="p-panel-desc">
                Remove pending/failed payments and transactions left
                behind after a gym is deleted.
              </p>
            </div>

            <button
              type="button"
              onClick={openCleanupConfirmation}
              disabled={cleanupLoading}
              style={{
                display: "inline-flex",
                alignItems: "center",
                gap: 8,
                padding: "10px 14px",
                borderRadius: 10,
                border: "1px solid rgba(255, 92, 92, .28)",
                background: "rgba(255, 92, 92, .08)",
                color: "#ff8585",
                cursor: cleanupLoading
                  ? "not-allowed"
                  : "pointer",
                opacity: cleanupLoading ? 0.6 : 1,
                fontWeight: 700,
                fontSize: 12,
              }}
            >
              <Trash2 size={15} />
              {cleanupLoading
                ? "Cleaning..."
                : "Clean up transactions"}
            </button>
          </div>

          <div
            style={{
              padding: 14,
              borderRadius: 12,
              background: "rgba(255, 92, 92, .045)",
              border:
                "1px solid rgba(255, 92, 92, .12)",
              fontSize: 11,
              color: "#98a5b6",
              lineHeight: 1.6,
            }}
          >
            <b style={{ color: "#ff8585" }}>
              Safety rule:
            </b>{" "}
            successful payments for an existing gym are never deleted by
            this cleanup action. The server also blocks this cleanup in
            production unless it is explicitly enabled with
            <code style={{ marginLeft: 4 }}>
              
            </code>.
          </div>
        </section>

        <div className="revenue-lower-stack">
          <section className="p-panel">
            <div className="p-panel-head">
              <div>
                <h3 className="p-panel-title">
                  Transaction ledger
                </h3>
                <p className="p-panel-desc">
                  Only verified GB platform payments are counted as revenue.
                </p>
              </div>
            </div>

            <div className="p-toolbar">
              <div className="p-search">
                <Search size={16} />
                <input
                  placeholder="Search gym, plan or reference..."
                  value={query}
                  onChange={(e) =>
                    setQuery(e.target.value)
                  }
                />
              </div>
            </div>

            {loading ? (
              <div className="p-empty">
                Loading revenue...
              </div>
            ) : (
              <div className="p-table-wrap">
                <table className="p-table">
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Gym</th>
                      <th>Plan</th>
                      <th>Reference</th>
                      <th>Amount</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {tx.length ? (
                      tx.map((x) => (
                        <tr key={x._id}>
                          <td>
                            {date(
                              x.paidAt ||
                                x.createdAt,
                            )}
                          </td>
                          <td>
                            <b>
                              {x.gym?.name || "—"}
                            </b>
                          </td>
                          <td>
                            {x.plan?.name || "—"}
                          </td>
                          <td className="p-muted">
                            {x.reference || "—"}
                          </td>
                          <td className="p-money">
                            {money(
                              x.amount,
                              x.currency,
                            )}
                          </td>
                          <td>
                            <span
                              className={`p-badge ${String(
                                x.status,
                              ).toLowerCase()}`}
                            >
                              {x.status}
                            </span>
                          </td>
                        </tr>
                      ))
                    ) : (
                      <tr>
                        <td colSpan="6">
                          <div className="p-empty">
                            No matching transactions.
                          </div>
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            )}
          </section>

          <section className="p-panel">
            <div className="p-panel-head">
              <div>
                <h3 className="p-panel-title">
                  Revenue by plan
                </h3>
                <p className="p-panel-desc">
                  Which SaaS plans are generating verified revenue.
                </p>
              </div>
            </div>

            {byPlan.length ? (
              <div className="p-health">
                {byPlan.map((p, i) => (
                  <div
                    className="p-health-row"
                    key={String(p._id || i)}
                  >
                    <span className="p-health-left">
                      <i className="p-dot" />
                      {p.plan || "Unknown plan"}
                    </span>
                    <strong>
                      {money(p.total)}
                    </strong>
                  </div>
                ))}
              </div>
            ) : (
              <div className="p-empty">
                No successful payments yet.
              </div>
            )}

            <div
              style={{
                marginTop: 16,
                padding: 14,
                borderRadius: 14,
                background:
                  "rgba(215,255,53,.045)",
                border:
                  "1px solid rgba(215,255,53,.12)",
                fontSize: 11,
                color: "#98a5b6",
                lineHeight: 1.6,
              }}
            >
              <b style={{ color: "#d7ff35" }}>
                Revenue rule:
              </b>{" "}
              member membership payments belong to the gym and are not
              included in this ledger.
            </div>
          </section>
        </div>
      </div>
    </div>
    </>
  )
}

function RevenueModal({ modal, onCancel, onConfirm }) {
  const isConfirm = modal.type === "confirm"
  const isSuccess = modal.type === "success"

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="revenue-modal-title"
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 1000,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 20,
        background: "rgba(0, 0, 0, .68)",
        backdropFilter: "blur(5px)",
      }}
    >
      <div
        style={{
          width: "min(440px, 100%)",
          borderRadius: 18,
          border: "1px solid rgba(255,255,255,.10)",
          background: "#111821",
          boxShadow: "0 24px 80px rgba(0,0,0,.45)",
          overflow: "hidden",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            padding: "18px 20px 12px",
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 10,
              color: isSuccess
                ? "#d7ff35"
                : isConfirm
                  ? "#ff8585"
                  : "#ff8585",
            }}
          >
            {isSuccess ? (
              <CircleCheck size={22} />
            ) : (
              <Trash2 size={21} />
            )}
            <h3
              id="revenue-modal-title"
              style={{
                margin: 0,
                fontSize: 17,
                color: "#fff",
              }}
            >
              {modal.title}
            </h3>
          </div>

          <button
            type="button"
            onClick={onCancel}
            aria-label="Close"
            style={{
              width: 32,
              height: 32,
              display: "grid",
              placeItems: "center",
              border: 0,
              borderRadius: 9,
              background: "rgba(255,255,255,.06)",
              color: "#98a5b6",
              cursor: "pointer",
            }}
          >
            <X size={17} />
          </button>
        </div>

        <div
          style={{
            padding: "4px 20px 20px",
            color: "#aab5c4",
            fontSize: 13,
            lineHeight: 1.65,
          }}
        >
          {modal.message}
        </div>

        <div
          style={{
            display: "flex",
            justifyContent: "flex-end",
            gap: 10,
            padding: "14px 20px 18px",
            borderTop: "1px solid rgba(255,255,255,.07)",
            background: "rgba(255,255,255,.018)",
          }}
        >
          {isConfirm ? (
            <>
              <button
                type="button"
                onClick={onCancel}
                style={{
                  padding: "10px 16px",
                  borderRadius: 10,
                  border: "1px solid rgba(255,255,255,.12)",
                  background: "rgba(255,255,255,.04)",
                  color: "#d5dbe3",
                  cursor: "pointer",
                  fontWeight: 700,
                  fontSize: 12,
                }}
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={onConfirm}
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  gap: 7,
                  padding: "10px 16px",
                  borderRadius: 10,
                  border: "1px solid rgba(255,92,92,.30)",
                  background: "rgba(255,92,92,.12)",
                  color: "#ff8f8f",
                  cursor: "pointer",
                  fontWeight: 800,
                  fontSize: 12,
                }}
              >
                <Trash2 size={15} />
                Clean up transactions
              </button>
            </>
          ) : (
            <button
              type="button"
              onClick={onCancel}
              style={{
                padding: "10px 18px",
                borderRadius: 10,
                border: "1px solid rgba(215,255,53,.22)",
                background: "rgba(215,255,53,.08)",
                color: "#d7ff35",
                cursor: "pointer",
                fontWeight: 800,
                fontSize: 12,
              }}
            >
              {isSuccess ? "Clear" : "Close"}
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

function Stat({
  label,
  value,
  icon: Icon,
  yellow,
}) {
  return (
    <div
      className={`p-stat ${yellow ? "yellow" : ""}`}
    >
      <div className="p-stat-icon">
        <Icon size={20} />
      </div>
      <div className="p-stat-label">
        {label}
      </div>
      <div className="p-stat-value">
        {value}
      </div>
      <div className="p-stat-sub">
        Verified GB SaaS activity
      </div>
    </div>
  )
}
