import { useEffect, useState } from "react"
import { CheckCircle2, Globe2, Mail, Settings as SettingsIcon } from "lucide-react"
import { platform } from "../../api/api"
import { err } from "../../utils/helpers"
import "../../styles/platform.css"
export default function Settings(){const [s,setS]=useState({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false)
 useEffect(()=>{platform.settings().then(d=>setS(d?.settings||{})).catch(e=>setError(err(e))).finally(()=>setLoading(false))},[]);const save=async()=>{setSaving(true);setSaved(false);try{const d=await platform.updateSettings(s);setS(d?.settings||s);setSaved(true)}catch(e){setError(err(e))}finally{setSaving(false)}}
 return <div className="platform-page"><div className="platform-wrap"><div className="platform-head"><div><div className="platform-eyebrow"><i/><SettingsIcon size={13}/>&nbsp; PLATFORM CONFIGURATION</div><h1>Settings</h1><p>Control the public GB platform identity, support contact and default currency.</p></div></div>{error&&<div className="p-alert error">{error}</div>}{saved&&<div className="p-alert success"><CheckCircle2 size={14} style={{verticalAlign:"middle",marginRight:6}}/>Settings saved successfully.</div>}
 <div className="platform-grid"><section className="p-panel"><div className="p-panel-head"><div><h3 className="p-panel-title">Platform identity</h3><p className="p-panel-desc">These values represent GB, not an individual gym.</p></div></div>{loading?<div className="p-empty">Loading settings...</div>:<div className="p-form-grid"><Field icon={Globe2} label="Platform name" value={s.platformName||""} onChange={v=>setS({...s,platformName:v})}/><Field icon={Mail} label="Support email" value={s.supportEmail||""} onChange={v=>setS({...s,supportEmail:v})}/><Field label="Default currency" value={s.currency||"NGN"} onChange={v=>setS({...s,currency:v})}/></div>}<div className="p-form-actions"><button className="p-btn primary" disabled={loading||saving} onClick={save}>{saving?"Saving...":"Save settings"}</button></div></section>
 <section className="p-panel"><div className="p-panel-head"><div><h3 className="p-panel-title">Platform principles</h3><p className="p-panel-desc">Rules the control center is built around.</p></div></div><div className="p-health"><Rule title="Tenant isolation" text="Each gym operates inside its own tenant boundary."/><Rule title="SaaS billing" text="Gym-to-GB subscription payments feed platform revenue."/><Rule title="Gym revenue" text="Member-to-gym payments stay inside the gym account."/><Rule title="Role security" text="Platform Owner access is separate from gym administration."/></div></section></div>
 </div></div>}
function Field({icon:Icon,label,value,onChange}){return <div className="p-field"><label>{label}</label><div style={{position:"relative"}}>{Icon&&<Icon size={15} style={{position:"absolute",left:12,top:13,color:"#748196"}}/>}<input style={Icon?{paddingLeft:36}:undefined} value={value} onChange={e=>onChange(e.target.value)}/></div></div>};function Rule({title,text}){return <div className="p-health-row"><span className="p-health-left"><i className="p-dot"/><span><b style={{display:"block",fontSize:12}}>{title}</b><span style={{display:"block",fontSize:10,color:"#748196",marginTop:3}}>{text}</span></span></span><CheckCircle2 size={16} style={{color:"#d7ff35"}}/></div>}
